// <auto-generated />
using Intropix_Movies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Intropix_Movies.Migrations
{
    [DbContext(typeof(Intropix_MoviesContext))]
    [Migration("20181020091123_Studio")]
    partial class Studio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Intropix_Movies.Models.Studio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Year_of_foundation");

                    b.HasKey("ID");

                    b.ToTable("Studio");
                });

            modelBuilder.Entity("Intropix_Movies.Models.Trailers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Lenght");

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<string>("Source_link");

                    b.Property<int>("Studio_id");

                    b.Property<string>("Summary");

                    b.Property<string>("filming_location");

                    b.HasKey("ID");

                    b.ToTable("Trailers");
                });
#pragma warning restore 612, 618
        }
    }
}
